# Generated by Django 4.0.5 on 2024-01-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
