# Generated by Django 4.0.5 on 2024-01-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_like_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='likes',
            new_name='like',
        ),
    ]
