# Generated by Django 4.0.5 on 2022-10-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(help_text='This is text that will show up on the list of blog. Write a short snippet of text to describe your blog post.', max_length=225),
        ),
    ]
