# Generated by Django 4.0.5 on 2022-10-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='yes', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(help_text='This text that will show up on the list of blogs page. Write a short snippet of text to describe your blog post.', max_length=225),
        ),
    ]
